bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
bower install --save mobile-angular-ui
